# Auto-generated by MDS BE/GEM5 (pipeline-stages.pl). Do not edit.
#
# LVX pipeline stages: the cycle each stage acts at. A result's
# dependence latency is its write stage minus LVX_STAGE_RR.

LVX_STAGE_ID = 0
LVX_STAGE_RR = 1
LVX_STAGE_E1 = 2
LVX_STAGE_E2 = 3
LVX_STAGE_CR = 4
LVX_STAGE_E3 = 4
LVX_STAGE_E4 = 5
LVX_STAGE_E5 = 6
LVX_STAGE_WB = 6
LVX_STAGE_SF = 16
LVX_STAGE_SR = 24
