#!/usr/bin/env python3
"""Emit bounds.inc: the range each opcode's operands are allowed to take.

decoded[] is not free-form.  Every METHOD in a behaviour carries the interval Width.pm
proved for it -- for a register operand the index into its file, for an immediate the
field's range, for a modifier its member count -- and that interval is exactly what lets
CodeGen give the operand a narrow C type.  Feed a value outside it and the boxed and
unboxed forms disagree, correctly, on an input the description says cannot occur.

This is not hypothetical and it is not a rounding error.  lvx_v2's XPL* place a byte at a
lane of a 512-bit XVR, and the three register classes that select the lane are bounded
`hi:3` (registerGj, shifted << 4), `hi:1` (registerGk, << 5) and **`hi:0`** (registerGl,
<< 6) -- registerGl names exactly one register, so its encoded index is always 0.  A
harness handing it a 1 makes `index << 6` overflow the uint8_t the analysis proved
sufficient, and 58 of 1453 opcodes "fail".  None of them is a bug.

So the ranges come from the description rather than from a guess here.  Reading them from
Opcode.table rather than from Behavior.tuple is deliberate: the tuple's pretty-printed tree
is emitted without the abstract values, so the numbers are not in it.

Usage: genbounds.py <Opcode.table>   -> bounds.inc
"""
import re
import sys

if len(sys.argv) != 2:
    sys.exit(__doc__)

text = open(sys.argv[1], errors="replace").read()

INT64_MIN, INT64_MAX = -(2**63), 2**63 - 1
MAXRANK = 16

rows = []
for m in re.finditer(r'<Opcode\s+ID=\s*"Opcode-([A-Za-z0-9_]+)-([A-Za-z0-9_]+)"', text):
    core, name = m.group(1), m.group(2)
    end = text.find("</Opcode>", m.end())
    body = text[m.end():end if end > 0 else len(text)]

    lo = [None] * MAXRANK
    hi = [None] * MAXRANK
    # (METHOD.%3(*hi:3,lo:0*)) -- and the biased forms (METHOD.%3:1(...)) share the rank,
    # so take the tightest interval seen for it.
    for mm in re.finditer(r'\(METHOD\.%(\d+)(?::\d+)?\(\*([^*]*)\*\)\)', body):
        rank = int(mm.group(1))
        if not 1 <= rank <= MAXRANK:
            continue
        attrs = dict(re.findall(r'(\w+):(-?\d+)', mm.group(2)))
        if "lo" not in attrs or "hi" not in attrs:
            continue
        l, h = int(attrs["lo"]), int(attrs["hi"])
        if l < INT64_MIN or h > INT64_MAX or h < l:
            continue                     # unbounded: leave it to the default
        i = rank - 1
        lo[i] = l if lo[i] is None else max(lo[i], l)
        hi[i] = h if hi[i] is None else min(hi[i], h)

    n = 0
    for i in range(MAXRANK):
        if lo[i] is not None and hi[i] is not None and hi[i] >= lo[i]:
            n = i + 1
    if n:
        rows.append(("%s_%s" % (core, name), n,
                     [lo[i] if lo[i] is not None else 0 for i in range(n)],
                     [hi[i] if hi[i] is not None else -1 for i in range(n)]))

out = [
    "/* GENERATED by genbounds.py -- do not edit.  See its docstring: an operand fed",
    "   outside the range the description proves for it is not a test, it is an input the",
    "   architecture says cannot happen. */",
    "typedef struct { const char *name; int n; long long lo[%d], hi[%d]; } Bounds;" % (MAXRANK, MAXRANK),
    "static const Bounds bounds[] = {",
]
for name, n, l, h in rows:
    out.append('  { "%s", %d, {%s}, {%s} },'
               % (name, n,
                  ",".join("%dLL" % v for v in l),
                  ",".join("%dLL" % v for v in h)))
out += ["};", ""]
open("bounds.inc", "w").write("\n".join(out))

unbounded = sum(1 for _, n, _, h in rows for v in h[:n] if v < 0)
print("%d opcodes with operand bounds -> bounds.inc (%d operands left unbounded)"
      % (len(rows), unbounded))
