#!/usr/bin/env python3
# Copyright (C) 2026 Liesme Tech.
# Benoît Dupont de Dinechin (benoit.dinechin@gmail.com).
# Distributed under the GNU General Public License, version 2 or later.
"""Emit regs.inc for a Behavior.tuple: the register constants its bodies reference,
and the base the harness must start decoded[] at.

The values are arbitrary -- a differential test only needs both generations to see the
same ones -- but two things about them are not.

They must be DISTINCT, so that a bug swapping two registers still shows up.

And they must be SMALL AND CONSECUTIVE, which is the part that is easy to get wrong.  A
behaviour turns a decoded operand into an index into its own register file by subtracting
that file's base (`decoded[2] - Register_lvx_v1_P0`), so decoded[] has to start at or above
the highest base or the index comes out negative -- see harness.c.  But the index is then
*shifted* for a multi-register operand (a pair, a quad, an XVR octuple: << 1, << 2, << 3),
and Width.pm bounds METHOD to its file's index range, which is what lets CodeGen give it a
narrow C type.  Spread the bases far apart and the indices get large, the shifted value
overflows that type, and the boxed and unboxed forms disagree -- on an input the
description says cannot occur.  Consecutive bases keep every index small.

It also writes shims.inc: which register files and which storages the bodies actually
touch.  That is core-specific too -- lvx_v1 has four register files, lvx_v2 fourteen (the
XVR octuples) plus a CS storage -- and hardcoding it in harness.c meant the harness only
ever compiled against one core.

Usage: genregs.py <Behavior.tuple>   -> regs.inc, shims.inc
"""
import re
import sys

if len(sys.argv) != 2:
    sys.exit(__doc__)

text = open(sys.argv[1], errors="replace").read()
names = sorted(set(re.findall(r"\bRegister_[A-Za-z0-9_]+", text)))
if not names:
    sys.exit("no Register_* symbols in %s" % sys.argv[1])

def touched(prefix):
    return sorted(set(re.findall(r"HELPER\(%s([A-Za-z0-9_]+)\)" % prefix, text)))

regfiles = sorted(set(touched("operandFromRegFile_")) | set(touched("operandToRegFile_")))
reads = touched("readFromStorage_")
writes = touched("writeToStorage_")

shims = [
    "/* GENERATED by genregs.py -- do not edit.  The register files and storages this",
    "   core's bodies actually touch. */",
]
shims += ["SHIM_REGFILE(%s)" % n for n in regfiles]
shims += ["SHIM_READ(%s)" % n for n in reads]
shims += ["SHIM_WRITE(%s)" % n for n in writes]
shims += [""]
open("shims.inc", "w").write("\n".join(shims))

lines = [
    "/* GENERATED by genregs.py -- do not edit.",
    "   Register file bases.  ALL ZERO, on purpose: a behaviour turns a decoded operand into",
    "   an index into its file by subtracting the base, so a nonzero base makes the index",
    "   negative for any decoded value below it -- and the index's interval is what lets",
    "   CodeGen give METHOD a narrow type.  With every base 0 the decoded value simply IS the",
    "   index, and bounds.inc keeps it inside the range the description proves.  The cost is",
    "   that a generator bug substituting one base register for another would not show; that",
    "   is not a class of bug the code generator can introduce, since it copies the symbol. */",
    "enum {",
]
lines += ["  %s = 0," % n for n in names]
lines += [
    "};",
    "",
    "/* LAO accessors the generated bodies use.  A differential test only needs them to be",
    "   deterministic and identical on both sides, so identity is fine. */",
    "#define ModifierMember_value(x) ((uint64_t)(x))",
    "",
]
open("regs.inc", "w").write("\n".join(lines))
print("%d register constants -> regs.inc; "
      "%d regfiles, %d storage reads, %d storage writes -> shims.inc"
      % (len(names), len(regfiles), len(reads), len(writes)))
