#!/usr/bin/perl -w
# Machine Description System (MDS)
#
# Copyright (C) 2005 STMicroelectronics.
#
# Stephen Clarke (Stephen.Clarke@st.com).
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

package TargInfo;

use strict;
use warnings "FATAL" => "all";

use XML::Parser::Expat;

use O64Target;
use O64;

# Issues:
# 1.  st200 implicit LR operands have to be specially recognized and
#     handled in buildOpen64OperandLists.  This should be fixed by
#     making them explicit in the chess/MDS.

our $Family = uc $ENV{FAMILY};
our $family = lc $Family;

sub operator_parameters {
    my $operator = shift;
    # Filter out Partial parameters that are not used by Open64
    return grep {
        my $usage = $_->attribute('usage');
        !defined $usage || $usage !~ /Partial/
      } $operator->children('Parameter');
}

sub isExtended {
    my $opcode = shift;
    return Target::isExtended($opcode);
}

sub isSynthetic {
    my $opcode = shift;
    my $instructionID = $opcode->attribute("instruction");
    my $instruction = &MDS::fetch($instructionID);
    return defined $instruction->attribute("synthetic");
}

sub printGenericHeader {
    my $file = shift;
    print $file <<'EOT';
/* -- This file is automatically generated -- */ 
/* 

  Copyright (C) 2002, 2004 ST Microelectronics, Inc.  All Rights Reserved. 

  This program is free software; you can redistribute it and/or modify it 
  under the terms of version 2 of the GNU General Public License as 
  published by the Free Software Foundation. 
  This program is distributed in the hope that it would be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

  Further, this software is distributed without any warranty that it is 
  free of the rightful claim of any third person regarding infringement 
  or the like.  Any license provided herein, whether implied or 
  otherwise, applies only to this software file.  Patent licenses, if 
  any, provided herein do not apply to combinations of this program with 
  other software, or any other product whatsoever. 
  You should have received a copy of the GNU General Public License along 
  with this program; if not, write the Free Software Foundation, Inc., 59 
  Temple Place - Suite 330, Boston MA 02111-1307, USA. 

  Contact information:  ST Microelectronics, Inc., 
  , or: 

  http://www.st.com 

  For further information regarding this notice, see: 

  http: 
*/ 

// AUTOMATICALLY GENERATED FROM MDS DATA BASE !!! 
EOT

}

sub makeOpen64ISAProperties {
    # Install generic ISA properties, then
    # call a target-specific function to synthesize the
    # rest.
    my %attribute_properties = (
        'ReadList'  => 'var_opnds',
        'WriteList' => 'var_opnds',
      );
    foreach my $operator (@Operator::table) {
        my @properties = split ' ', ($operator->{O64}{PROPERTIES} || "");
        my @attributes = split ' ', ($operator->attribute("attributes") || "");
        push @properties, (map $attribute_properties{$_},
            grep $attribute_properties{$_}, @attributes);
        $operator->{O64}{PROPERTIES} = join ' ', @properties;
    }
    Target::makeTargetISAProperties();
    Target::makeTargetOperandProperties();
}

sub sort_operators {
    # [SC] Operator sorting has become very complicated, in an
    # attempt to preserve the ordering compared to old code
    # which used the opcode table.
    @Operator::table = sort {
        my $name1 = uc($a->name());
        my $name2 = uc($b->name());
        $name1 =~ s/\W/_/g;
        $name2 =~ s/\W/_/g;
        # [SC] ST200 hack, to ensure that the immediate operand is
        # last in opds, so it is least significant in comparison, so
        # that operations with extended immediates end up adjacent to their
        # unextended equivalents, as required by verify_operators.
        # [BD3] The new Operator names yields an order good enough so keep it.
        #	print STDERR "sort_operators $name1 $name2\n";
        ($name1 cmp $name2) ||
          ($a->attribute("ID") cmp $b->attribute("ID"));
      } @Operator::table;
}

sub verify_operators {
    # Specific operator ordering is no longer required by the open64.
}

sub annotateMDS {
    &O64::makeNames;
    # Sort operators by open64 instruction name, so
    # this must be done after creating the open64
    # instruction names.
    sort_operators;
    verify_operators;
    makeOpen64ISAProperties;
}

my %usefulGeneric = (
    LABEL=>	1,
    PHI=>	        1,
    PSI=>	        1,
    PCOPY=>	1,
    SIGMA=>	1,
    KILL=>	1,
    SKIP=>	1,
    COPY=>	1,
    TEST=>	1,
    APPLY=>	1,
    FWDBAR=>	1,
    BWDBAR=>	1,
    IFIXUP=>	1,
    BEGIN_PREGTN=>	1,
    END_PREGTN=>	1,
  );

sub readMDS {
    foreach my $filename (@_) {
        my $fh;
        open $fh, $filename;
        &MDS::parse($fh);
    }
    # Remove some Operator(s) from MDS processing.
    my @operators = grep {
        my ($origins) = $_->access("origins");
        my $mnemonic = $_->attribute("mnemonic");
        my $type = $origins->type();
        $type ne 'Generic' or $usefulGeneric{$mnemonic} or Target::usefulGeneric($mnemonic);
      } @Operator::table;
    @Operator::table = @operators;
}

sub write_annotation {
    my ($file, $key, $id, $element, $ancestry) = @_;
    my $annots = $element->{$key};
    if (keys %$annots) {
        print $file "<$key\n  AnnotID=  \"$id\"\n";
        if (scalar @$ancestry) {
            print $file "  AnnotANCESTRY=  \"", join ' ', @$ancestry, "\"\n";
        }
        foreach my $key2 (sort keys %$annots) {
            my $value = join ' ', (split ' ', $$annots{$key2});
            print $file "  $key2=\t\"$value\"\n";
        }
        print $file "/>";
    }
    my $children = &MDS::contents($element);
    foreach my $i (0..(scalar @$children)-1) {
        my $child = $$children[$i];
        if (ref $child) {
            push @$ancestry, $i;
            &write_annotation ($file, $key, $id, $child, $ancestry);
            pop @$ancestry;
        }
    }
}

sub writeAnnotations {
    my ($file, $key) = @_;

    foreach my $name (sort keys %MDS::table) {
        &write_annotation ($file, $key, $name, $MDS::table{$name}, []);
    }
    print $file "\n";
}

sub parse {
    my $handle = shift;
    my $p1 = new XML::Parser::Expat;
    $p1->setHandlers(
        Start => sub {
            shift;
            my $element = shift;
            my %attributes = @_;
            if (exists $attributes{"AnnotID"}) {
                my $mds_element = &MDS::fetch ($attributes{"AnnotID"});
                delete $attributes{"AnnotID"};
                my $ancestry = $attributes{"AnnotANCESTRY"} || "";
                my @ancestry = split ' ', $ancestry;
                delete $attributes{"AnnotANCESTRY"};
                while (@ancestry) {
                    my $c = shift @ancestry;
                    $mds_element = ${&MDS::contents($mds_element)}[$c];
                }
                $mds_element->{$element} = \%attributes;
            }
          },
      );
    local $/ = undef;
    $p1->parse(<$handle>);
}

sub readAnnotations {
    my ($filenames) = @_;
    my @annotations = split ' ', $filenames;
    foreach my $filename (@annotations) {
        my $file;
        open ($file, $filename) || die "Cannot open annotations file $filename\n";
        &parse ($file);
    }
    sort_operators;
    verify_operators;
}

1;
# vim: set ts=4 sw=4 et:
