# Parse the language described in Takumi.output.
# Perl source code automatically generated by yaxcc.pl Revision: 1.3.
# Source code copyright 1995 M-J. Dominus (mjd@pobox.com)

# code included from 
# Machine Description System (MDS)
#
# Copyright (C) 2005 STMicroelectronics
#
# Benoit Dupont de Dinechin (Benoit.Dupont-de-Dinechin@st.com).
# Christophe Guillon (Christophe.Guillon@st.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

package Takumi;
use Carp;
use warnings;
use Behavior;

=head1 NAME

Takumi -- Takumi language parser

=head1 SYNOPSIS

  use Takumi;

  &Takumi::yyin(@input);
  &Takumi::yyparse && die "syntax error at ", &Takumi::yylval;
  &Takumi::yyflush;

=head1 DESCRIPTION

=head1 FUNCTIONS

=over 4

=item B<stage>($stage, $substage);

Sets the default ($stage, $substage) stage information for the following parsing.

=item B<yyin>($input);

Fills the input buffer for $input parsing.

=item B<yyparse>();

Parse the input buffer, returning non-zero on failure.

=item B<yylval>($size);

Sets the number of tokens memorized before the current
token. Useful to display error messages.

=item B<yyflush>();

Flush the input buffer. Useful after an error has been
detected, so as to start with a new, clean buffer.

=item B<yytree>();

Returns the parse tree. Use Data::Dumper to figure what it is.

=back 

=head1 LIMITATIONS

=head1 AUTHOR

Benoit Dupont de Dinechin
Christophe Guillon

=cut

#
# Specific initalization
#
my $Stage;
my $Substage;
sub stage {
  my ($stage_substage) = @_;
  $stage_substage =~ /^((\d+))?(_(\d+))?/;
  ($Stage, $Substage) = ($2, $4);
}

my %names_to_ignore = ( LOCK_ADDRESS => 1 );
sub ignore_name {
  my $name = shift;
  return exists $names_to_ignore{$name};
}

#
# Scanner code: export &yylval, &yyin, &yylex.
#

our $yylval = undef;
our @yylval = ();
our $yylkeep = 8;
sub yylval {
  $yylkeep =  shift;
  if (defined $yylkeep) {
    shift @yylval while @yylval > $yylkeep;
  }
  map { "'$_' " } @yylval;
}

our @yyin = ();
sub yyin {
  while (@_) {
    my $buffer = shift;
    push @yyin, grep {length($_)} split ' ', $buffer;
  }
}

sub yyflush {
  @yyin = ();
  @yylval = ();
}

my $yytree;
sub yytree {
  return $yytree;
}

sub yylex {
  my $token;
  return '' unless (@yyin);
  my $value = shift @yyin;
  #%token BINNUM HEXNUM DECNUM SYMNUM IDENT
  #%token IF ELSE THROW DbgThrow REPEAT FROM FOR
  #%token NOT INT OR XOR AND
  if ($value =~ s/^(0x[0-9a-fA-F]+)//) {
    ($token, $yylval) = ('HEXNUM', $1);
    $yylval = oct($yylval) if $yylval =~ /^0/;
  } elsif ($value =~ s/^(0b[01]+)//) {
    ($token, $yylval) = ('BINNUM', $1);
    $yylval = oct($yylval) if $yylval =~ /^0/;
  } elsif ($value =~ s/^(\-?\d+)//) {
    ($token, $yylval) = ('DECNUM', $1);
  } elsif ($value =~ s/^(IF|ELSE|THROW|DbgThrow|REPEAT|FROM|FOR|NOT|INT|OR|XOR|AND)\b//) {
    ($token, $yylval) = ($1, $1);
  } elsif ($value =~ s/^stage_((\d+)?_(\d+))?\b//) {
    ($token, $yylval) = ('STAGE', $1);
  } elsif ($value =~ s/^([a-zA-Z_]\w*)//) {
    ($token, $yylval) = ('IDENT', $1);
    $token = 'SYMNUM' if defined &Constant($yylval);
  } elsif ($value =~ s/^((\>\>)|(\<\<)|([<>=!]=)|(\W))//) {
    ($token, $yylval) = ($1, $1);
  } else {
    croak "unrecognized token: $value";
  }
  unshift @yyin, $value if length($value);
  if (defined $yylkeep) {
    push @yylval, $yylval;
    shift @yylval if @yylval > $yylkeep;
  }
  $token;
}

# Map Takumi function names.
my %yyfunc = (
  CountLeadingZeros=> [ 'CLZ', 32, { TYPE=>'Integer'} ],
  #IDivIeee=> [ 'DIVI' ],
  #UIDivIeee=> [ 'DIVU' ],
  #IRemIeee=> [ 'REMI' ],
  #UIRemIeee=> [ 'REMU' ],
  IsCRegSpace=> [ 'FALSE', { TYPE=>'Boolean' } ],
  IsDBreakHit=> [ 'FALSE', { TYPE=>'Boolean' } ],
  IsDBreakLoadHit=> [ 'FALSE', { TYPE=>'Boolean' } ],
  IsDBreakStoreHit=> [ 'FALSE', { TYPE=>'Boolean' } ],
  IsDBreakPrefetchHit=> [ 'FALSE', { TYPE=>'Boolean' } ],
  IsDebugDBreakLoadHit=> [ 'FALSE', { TYPE=>'Boolean' } ],
  IsDebugDBreakStoreHit=> [ 'FALSE', { TYPE=>'Boolean' } ],
  IsDebugDBreakPrefetchHit=> [ 'FALSE', { TYPE=>'Boolean' } ],
  ReadCheckMemory=> [ 'SKIP', { } ],
  ReadCheckLockMemory=> [ 'SKIP', { } ],
  DisReadCheckMemory=> [ 'SKIP', { } ],
  WriteCheckMemory=> [ 'SKIP', { } ],
  WriteCheckLockMemory=> [ 'SKIP', { } ],
  PrefetchCheckMemory=> [ 'SKIP', { } ],
  PurgeAddressCheckMemory=> [ 'SKIP', { } ],
  PurgeInvalidateAddressCheckMemory=> [ 'SKIP', { } ],
  AbortWriteMemory_=> [ 'SKIP', { } ],
);
sub yyfunc {
  my ($name, @arguments) = @_;
  my $yyfunc = $yyfunc{$name};
  if (defined $yyfunc) {
    my @yyfunc = @{$yyfunc};
    splice @yyfunc, -1, 0, @arguments;
    $yyfunc = \@yyfunc;
  }
  return $yyfunc;
}

sub substitute_repeat_var {
  my ($this, $name, $value) = @_;
  if (ref $this eq 'ARRAY') {
    if ($this->[0] eq 'READ') {
      if ($this->[1] eq $name) {
        return &CONST($value);
      }
    }
    my @that; map {
      push @that, &substitute_repeat_var($_, $name, $value);
    } @{$this};
    return \@that;
  } elsif (ref $this eq 'HASH') {
    my %that = %{$this};
    return \%that;
  } elsif (!ref $this) {
    return $this;
  }
  return undef;
}

sub do_repeat {
  my ($name, $from, $count, $step, $body) = @_;
  my @values = map { $from + ($step * $_); } (0..$count-1);
  my @body = map { &substitute_repeat_var ($body, $name, $_) ; } @values;
  return &SEQ(@body);
}

my @Accesses;

# generating or using semantic actions from 
our @sem = (
# rule 0
sub { },
# rule 1
# takumi -> statements
sub {
$yytree = &SEQ(@Accesses, $_[0]);
@Accesses = ();
$Stage = undef;
$Substage = undef;
#print STDERR &Pretty($yytree, "  ");
},
# rule 2
# statements -> $empty
sub {
&SEQ();
},
# rule 3
# statements -> statements statement
sub {
return $_[0] unless ref $_[1];
&SEQ($_[0], $_[1]);
},
# rule 4
# statement -> STAGE
sub {
&Takumi::stage($_[0]);
},
# rule 5
# statement -> IF '(' expression ')' block_or_statement
sub {
&IF($_[2], $_[4], &SKIP());
},
# rule 6
# statement -> IF '(' expression ')' block_or_statement ELSE block_or_statement
sub {
&IF($_[2], $_[4], $_[6]);
},
# rule 7
# statement -> variable '=' expression ';'
sub {
my ($name, $start, $count) = @{$_[0]};
my $symbol = &Behavior::Symbol($name);
my $storage = &Behavior::Storage($name);
if (&ignore_name ($name)) {
  return &SKIP();
} elsif (defined $symbol) {
  my $stage = defined $symbol->{STAGES}? $symbol->{STAGES}->[-1]: $Stage;
  if (defined $start && defined $count) {
    return &STORE($stage, &AGGL($name, $start, $count), $_[2]);
  } elsif (defined $symbol->{KIND} && $symbol->{KIND} eq 'Register') {
    my ($storage, $address, $extent) = ($symbol->{STORAGE}, $symbol->{ADDRESS}, $symbol->{EXTENT});
    return &STORE($stage, &AGGL($storage, &CONST($address), &CONST($extent)), $_[2]);
  }
  my $proxy = $symbol->{PROXY};
  if (defined $proxy) {
    die "Multiple commits to proxy $proxy" if defined $proxy->{COMMITS};
    &Symbol($proxy, { EXTEND=>$extend, WIDTH=>$symbol->{WIDTH}, COMMITS=>1 });
    return &SEQ(&WRITE($name, $_[2]), &COMMIT($stage, $proxy, &READ($name)));
  }
  &WRITE($name, $_[2]);
} elsif (defined $storage) {
  my $stage = defined $storage->{STAGES}? $storage->{STAGES}->[-1]: $Stage;
  $start = &CONST(0) unless defined $start;
  $count = &CONST(1) unless defined $count;
  return &STORE($stage, &AGGL($name, $start, $count), $_[2]);
} else { croak "Write unknown variable $name"; }
},
# rule 8
# statement -> IDENT '(' opt_arguments ')' ';'
sub {
my ($name, @arguments) = ($_[0], @{$_[2]});
my $mem_stage = $Stage;
if ($name =~ /^ReadMemory_(\d+)_$/) {
  my ($width, $address) = ($1, @arguments);
  &Symbol('mem_response', { WIDTH=>$width });
  my $load = &LOAD($mem_stage, &AGGL('MEM', $address, &CONST($width/8)));
  return &WRITE('mem_response', $load);
} elsif ($name =~ /^DisReadMemory_(\d+)_$/) {
  my ($width, $address) = ($1, @arguments);
  &Symbol('mem_response', { WIDTH=>$width });
  my $load = &LOAD($mem_stage, &AGGL('MEM', $address, &CONST($width/8)));
  my $probe = &PROBE($mem_stage, &AGGL('MEM', &Clone($address), &CONST($width/8)));
  my $writeOK = &WRITE('mem_response', $load);
  my $writeKO = &WRITE('mem_response', &CONST(0));
  return &IF($probe, $writeOK, $writeKO);
} elsif ($name =~ /^ReadLockMemory_(\d+)_$/) {
  my ($width, $address) = ($1, @arguments);
  &Symbol('mem_response', { WIDTH=>$width });
  my $load = &LOAD($mem_stage, &AGGL('MEM', $address, &CONST($width/8)));
#  my $lock_value = &IOR(&Clone($address), &CONST(1));
#  my $lock = &STORE($mem_stage, &AGGL('LOCK_ADDRESS', &CONST('LOCKED'), &CONST(32)), &I2F(&CONST(32), $lock_value));
  my $write = &WRITE('mem_response', $load);
#  return &SEQ($write, $lock);
  return $write;
} elsif ($name  =~ /^ReadMemMultiple_(\d+)_$/) {
  my ($width, $address, $count) = ($1, @arguments);
  &Symbol('mem_read_queue', { TYPE=>'Integer' });
  my $extent = &MUL($count, &CONST($width/8));
  my $load = &LOAD($mem_stage, &AGGL('MEM', $address, $extent));
  my $field = &F2I(&MUL(&Clone($count), &CONST($width)), $load);
  return &WRITE('mem_read_queue', $field);
} elsif ($name =~ /^ReadMemResponseMultiple_(\d+)_$/) {
  my $width = $1;
  &Symbol('mem_read_queue', { TYPE=>'Integer' });
  my $read = &READ('mem_read_queue');
  return &EFFECT($mem_stage, 'ReadMultiple', &CONST($width), $read, @arguments);
} elsif ($name =~ /^WriteMemory_(\d+)_$/) {
  my ($width, $address, $value) = ($1, @arguments);
  return &STORE($mem_stage, &AGGL('MEM', $address, &CONST($width/8)), $value);
} elsif ($name =~ /^WriteLockMemory_(\d+)_$/) {
  my ($width, $address, $value) = ($1, @arguments);
  my $store = &STORE($mem_stage, 'MEM', &AGGL($address, &CONST($width/8)), $value);
#  my $unlock = &STORE($mem_stage, &AGGL('LOCK_ADDRESS', &CONST('LOCKED'), &CONST(1)), &I2F(&CONST(1), &CONST(0)));
#  return &SEQ($store, $unlock);
  return $store;
} elsif ($name =~ /^WriteMemMultiple_(\d+)_$/) {
  my ($width, $address, $count, @value) = ($1, @arguments);
  my $value = &APPLY('WriteMultiple', &CONST($width), $count, @value);
  my $extent = &MUL(&Clone($count), &CONST($width/8));
  my $field = &I2F(&MUL(&Clone($count), &CONST($width)), $value);
  return &STORE($mem_stage, &AGGL('MEM', $address, $extent), $field);
} else {
  my $yyfunc;
  if ($name =~ /^(\w+)_(\d+)_$/ &&
      defined ($yyfunc = &yyfunc($1, $2, @arguments)) ||
      defined ($yyfunc = &yyfunc($name, @arguments))) {
    return $yyfunc;
  }
}
&EFFECT($Stage, $name, @arguments);
},
# rule 9
# statement -> THROW '(' IDENT ')' ';'
sub {
&THROW($Stage, $_[2]);
},
# rule 10
# statement -> DbgThrow '(' IDENT ')' ';'
sub {
&THROW($Stage, $_[2]);
},
# rule 11
# statement -> REPEAT IDENT FROM constant FOR constant block_or_statement
sub {
&do_repeat($_[1], $_[3], $_[5], 1, $_[6]);
},
# rule 12
# statement -> REPEAT IDENT FROM constant FOR constant STEP constant block_or_statement
sub {
&do_repeat($_[1], $_[3], $_[5], $_[7], $_[8]);
},
# rule 13
# block_or_statement -> statement
sub {
$_[0];
},
# rule 14
# block_or_statement -> block
sub {
$_[0];
},
# rule 15
# block -> '{' statements '}'
sub {
$_[1];
},
# rule 16
# variable -> IDENT
sub {
[ $_[0] ];
},
# rule 17
# variable -> IDENT '[' expression ']'
sub {
[ $_[0], $_[2], &CONST(1) ];
},
# rule 18
# variable -> IDENT '[' expression FOR expression ']'
sub {
[ $_[0], $_[2], $_[4] ];
},
# rule 19
# expression -> nested_expression
sub {
$_[0];
},
# rule 20
# expression -> nested_expression operator2 nested_expression
sub {
&{"Behavior::$_[1]"}($_[0], $_[2]);
},
# rule 21
# expression -> operator1 nested_expression
sub {
&{"Behavior::$_[0]"}($_[1]);
},
# rule 22
# nested_expression -> constant
sub {
&CONST($_[0]);
},
# rule 23
# nested_expression -> variable
sub {
my ($name, $start, $count) = @{$_[0]};
my $symbol = &Behavior::Symbol($name);
my $storage = &Behavior::Storage($name);
if (defined $symbol) {
  my ($extend, $width) = ($symbol->{EXTEND}, $symbol->{WIDTH});
  my $stage = defined $symbol->{STAGES}? $symbol->{STAGES}->[0]: $Stage;
  if (defined $start && defined $count) {
    die "FIXME! Likely broken, never used code!";
  } elsif (defined $symbol->{KIND} && $symbol->{KIND} eq 'Register') {
    my ($storage, $address, $extent) = ($symbol->{STORAGE}, $symbol->{ADDRESS}, $symbol->{EXTENT});
    my $load = &LOAD($stage, &AGGL($storage, &CONST($address), &CONST($extent)));
    my $f2i = &F2I(&CONST($width), $load);
    return &ZX($width, $f2i) if $extend eq 'ZX';
    return &SX($width, $f2i) if $extend eq 'SX';
    croak "Invalid EXTEND $extend for $name";
  } else {
    my $proxy = $symbol->{PROXY};
    if (defined $proxy) {
      die "Multiple accesses to proxy $proxy" if defined $proxy->{ACCESSES};
      &Symbol($proxy, { EXTEND=>$extend, WIDTH=>$width, ACCESSES=>1 });
      push @Accesses, &WRITE($name, &{"Behavior::$extend"}($width, &ACCESS($stage, $proxy)));
    }
    return &READ($name);
  }
} elsif (defined $storage) {
#  if ($name eq 'PSW'
#      && defined $start
#      && defined &Behavior::Storage("DEBUG_MODE")
#      && $start == &Behavior::Storage("DEBUG_MODE")) {
  if ($name eq 'PSW'
      && $start->[0] eq 'CONST'
      && $start->[1] eq 'DEBUG_MODE') {
    return &CONST(0);
  }
  my $stage = defined $storage->{STAGES}? $storage->{STAGES}->[0]: $Stage;
  $start = &CONST(0) unless defined $start;
  $count = &CONST(1) unless defined $count;
  return &LOAD($stage, &AGGL($name, $start, $count));
} else { croak "Read unknown variable $name"; }
},
# rule 24
# nested_expression -> IDENT '(' opt_arguments ')'
sub {
my ($name, @arguments) = ($_[0], @{$_[2]});
if ($name eq 'Bit') {
  my $start = $arguments[1];
  my $shr = &SHR($arguments[0], $start);
  return &ZX(1, $shr);
} elsif ($name eq 'BitsOf') {
  my $start = $arguments[1];
  my $width = $arguments[2]->[1];
  my $shr = &SHR($arguments[0], $start);
  return &ZX($width, $shr);
} elsif ($name eq 'Register') {
  return &ZX(32, $arguments[0]);
} elsif ($name =~ /^ZeroExtend_(\d+)_$/) {
  return &ZX($1, $arguments[0]);
} elsif ($name =~ /^SignExtend_(\d+)_$/) {
  return &SX($1, $arguments[0]);
} elsif ($name =~ /^Saturate_(\d+)_$/) {
  return &SAT($1, $arguments[0]);
} elsif ($name =~ /^Overflow_(\d+)_$/) {
  return &NE(&SAT($1, $arguments[0]), $arguments[0]);
} elsif ($name =~ /^UnsignedExtract_(\d+)_$/) {
  my ($width, $value, $idx) = ($1, $arguments[0], $arguments[1]);
  return &ZX($width, &SHR($value, &MUL($idx, &CONST($width))));
} elsif ($name =~ /^SignedExtract_(\d+)_$/) {
  my ($width, $value, $idx) = ($1, $arguments[0], $arguments[1]);
  return &SX($width, &SHR($value, &MUL($idx, &CONST($width))));
} elsif ($name =~ /^MaskAndShift_(\d+)_$/) {
  my ($width, $value, $idx) = ($1, $arguments[0], $arguments[1]);
  return &SHL(&ZX($width, $value), &MUL($idx, &CONST($width)));
} elsif ($name =~ /^RotateRight_(\d+)_$/) {
  my $width = $1;
  my $value = $arguments[0];
  my $count = $arguments[1];
  return &ROR($width, $value, $count);
} elsif ($name =~ /^ReadMemResponse(_(\d+)_)?$/) {
  &Symbol('mem_response', { WIDTH=>$1 });
  return &READ('mem_response');
} elsif ($name =~ /^ReadMemResponseMultiple_(\d+)_$/) {
  my $width = $1;
  &Symbol('mem_read_queue', { TYPE=>'Integer' });
  my $read = &READ('mem_read_queue');
  return &APPLY('ReadMultiple', &CONST($width), $read, @arguments);
} else {
  my $yyfunc;
  if ($name =~ /^(\w+)_(\d+)_$/ &&
      defined ($yyfunc = &yyfunc($1, $2, @arguments)) ||
      defined ($yyfunc = &yyfunc($name, @arguments))) {
    return $yyfunc;
  }
}
&APPLY($name, @arguments);
},
# rule 25
# nested_expression -> '(' expression ')'
sub {
$_[1];
},
# rule 26
# constant -> DECNUM
sub {
$_[0];
},
# rule 27
# constant -> HEXNUM
sub {
$_[0];
},
# rule 28
# constant -> BINNUM
sub {
$_[0];
},
# rule 29
# constant -> SYMNUM
sub {
$_[0];
},
# rule 30
# opt_arguments -> $empty
sub {
[ ];
},
# rule 31
# opt_arguments -> arguments
sub {
$_[0];
},
# rule 32
# arguments -> argument
sub {
[ $_[0] ];
},
# rule 33
# arguments -> arguments ',' argument
sub {
[ @{$_[0]}, $_[2] ];
},
# rule 34
# argument -> expression
sub {
$_[0];
},
# rule 35
# operator1 -> '~'
sub {
'NOT';
},
# rule 36
# operator1 -> '-'
sub {
'NEG';
},
# rule 37
# operator1 -> NOT
sub {
'NOTL';
},
# rule 38
# operator1 -> INT
sub {
'B2I';
},
# rule 39
# operator2 -> '+'
sub {
'ADD';
},
# rule 40
# operator2 -> '-'
sub {
'SUB';
},
# rule 41
# operator2 -> '*'
sub {
'MUL';
},
# rule 42
# operator2 -> '&'
sub {
'AND';
},
# rule 43
# operator2 -> '|'
sub {
'IOR';
},
# rule 44
# operator2 -> '^'
sub {
'XOR';
},
# rule 45
# operator2 -> AND
sub {
'ANDL';
},
# rule 46
# operator2 -> OR
sub {
'IORL';
},
# rule 47
# operator2 -> XOR
sub {
'XORL';
},
# rule 48
# operator2 -> ">>"
sub {
'SHR';
},
# rule 49
# operator2 -> "<<"
sub {
'SHL';
},
# rule 50
# operator2 -> ">="
sub {
'GE';
},
# rule 51
# operator2 -> "<="
sub {
'LE';
},
# rule 52
# operator2 -> "=="
sub {
'EQ';
},
# rule 53
# operator2 -> "!="
sub {
'NE';
},
# rule 54
# operator2 -> '<'
sub {
'LT';
},
# rule 55
# operator2 -> '>'
sub {
'GT';
},
);

our @act = (
{# state 0
  'statements'=>['goto','2'],
  'takumi'=>['goto','1'],
  '$default'=>['reduce','2'],
},
{# state 1
  '$end'=>['shift','3'],
},
{# state 2
  'statement'=>['goto','10'],
  'IDENT'=>['shift','4'],
  'variable'=>['goto','11'],
  'IF'=>['shift','6'],
  'THROW'=>['shift','7'],
  'STAGE'=>['shift','5'],
  '$default'=>['reduce','1'],
  'REPEAT'=>['shift','9'],
  'DbgThrow'=>['shift','8'],
},
{# state 3
  '$default'=>['accept','undef'],
},
{# state 4
  '$default'=>['reduce','16'],
  '['=>['shift','13'],
  '('=>['shift','12'],
},
{# state 5
  '$default'=>['reduce','4'],
},
{# state 6
  '('=>['shift','14'],
},
{# state 7
  '('=>['shift','15'],
},
{# state 8
  '('=>['shift','16'],
},
{# state 9
  'IDENT'=>['shift','17'],
},
{# state 10
  '$default'=>['reduce','3'],
},
{# state 11
  '='=>['shift','18'],
},
{# state 12
  'nested_expression'=>['goto','31'],
  'BINNUM'=>['shift','19'],
  'DECNUM'=>['shift','21'],
  'IDENT'=>['shift','23'],
  '$default'=>['reduce','30'],
  'INT'=>['shift','25'],
  'variable'=>['goto','29'],
  'HEXNUM'=>['shift','20'],
  'opt_arguments'=>['goto','33'],
  '~'=>['shift','27'],
  'expression'=>['goto','30'],
  'argument'=>['goto','35'],
  'arguments'=>['goto','34'],
  'operator1'=>['goto','36'],
  'NOT'=>['shift','24'],
  'SYMNUM'=>['shift','22'],
  'constant'=>['goto','32'],
  '-'=>['shift','28'],
  '('=>['shift','26'],
},
{# state 13
  'expression'=>['goto','37'],
  '~'=>['shift','27'],
  'operator1'=>['goto','36'],
  'SYMNUM'=>['shift','22'],
  'NOT'=>['shift','24'],
  '('=>['shift','26'],
  'constant'=>['goto','32'],
  '-'=>['shift','28'],
  'BINNUM'=>['shift','19'],
  'nested_expression'=>['goto','31'],
  'DECNUM'=>['shift','21'],
  'INT'=>['shift','25'],
  'IDENT'=>['shift','23'],
  'variable'=>['goto','29'],
  'HEXNUM'=>['shift','20'],
},
{# state 14
  'expression'=>['goto','38'],
  '~'=>['shift','27'],
  'operator1'=>['goto','36'],
  '('=>['shift','26'],
  'constant'=>['goto','32'],
  '-'=>['shift','28'],
  'SYMNUM'=>['shift','22'],
  'NOT'=>['shift','24'],
  'BINNUM'=>['shift','19'],
  'nested_expression'=>['goto','31'],
  'INT'=>['shift','25'],
  'IDENT'=>['shift','23'],
  'DECNUM'=>['shift','21'],
  'HEXNUM'=>['shift','20'],
  'variable'=>['goto','29'],
},
{# state 15
  'IDENT'=>['shift','39'],
},
{# state 16
  'IDENT'=>['shift','40'],
},
{# state 17
  'FROM'=>['shift','41'],
},
{# state 18
  'expression'=>['goto','42'],
  '~'=>['shift','27'],
  'operator1'=>['goto','36'],
  '('=>['shift','26'],
  '-'=>['shift','28'],
  'constant'=>['goto','32'],
  'SYMNUM'=>['shift','22'],
  'NOT'=>['shift','24'],
  'BINNUM'=>['shift','19'],
  'nested_expression'=>['goto','31'],
  'INT'=>['shift','25'],
  'IDENT'=>['shift','23'],
  'DECNUM'=>['shift','21'],
  'HEXNUM'=>['shift','20'],
  'variable'=>['goto','29'],
},
{# state 19
  '$default'=>['reduce','28'],
},
{# state 20
  '$default'=>['reduce','27'],
},
{# state 21
  '$default'=>['reduce','26'],
},
{# state 22
  '$default'=>['reduce','29'],
},
{# state 23
  '$default'=>['reduce','16'],
  '('=>['shift','43'],
  '['=>['shift','13'],
},
{# state 24
  '$default'=>['reduce','37'],
},
{# state 25
  '$default'=>['reduce','38'],
},
{# state 26
  'expression'=>['goto','44'],
  '~'=>['shift','27'],
  'operator1'=>['goto','36'],
  'SYMNUM'=>['shift','22'],
  'NOT'=>['shift','24'],
  '('=>['shift','26'],
  '-'=>['shift','28'],
  'constant'=>['goto','32'],
  'BINNUM'=>['shift','19'],
  'nested_expression'=>['goto','31'],
  'DECNUM'=>['shift','21'],
  'INT'=>['shift','25'],
  'IDENT'=>['shift','23'],
  'variable'=>['goto','29'],
  'HEXNUM'=>['shift','20'],
},
{# state 27
  '$default'=>['reduce','35'],
},
{# state 28
  '$default'=>['reduce','36'],
},
{# state 29
  '$default'=>['reduce','23'],
},
{# state 30
  '$default'=>['reduce','34'],
},
{# state 31
  '*'=>['shift','50'],
  '<<'=>['shift','55'],
  '<='=>['shift','57'],
  '$default'=>['reduce','19'],
  '<'=>['shift','60'],
  '|'=>['shift','52'],
  '+'=>['shift','49'],
  '!='=>['shift','59'],
  '>>'=>['shift','54'],
  'XOR'=>['shift','46'],
  'AND'=>['shift','47'],
  '&'=>['shift','51'],
  '^'=>['shift','53'],
  '=='=>['shift','58'],
  '>'=>['shift','61'],
  'OR'=>['shift','45'],
  '>='=>['shift','56'],
  'operator2'=>['goto','62'],
  '-'=>['shift','48'],
},
{# state 32
  '$default'=>['reduce','22'],
},
{# state 33
  ')'=>['shift','63'],
},
{# state 34
  '$default'=>['reduce','31'],
  ','=>['shift','64'],
},
{# state 35
  '$default'=>['reduce','32'],
},
{# state 36
  'HEXNUM'=>['shift','20'],
  'variable'=>['goto','29'],
  'IDENT'=>['shift','23'],
  'DECNUM'=>['shift','21'],
  'BINNUM'=>['shift','19'],
  'nested_expression'=>['goto','65'],
  '('=>['shift','26'],
  'constant'=>['goto','32'],
  'SYMNUM'=>['shift','22'],
},
{# state 37
  'FOR'=>['shift','66'],
  ']'=>['shift','67'],
},
{# state 38
  ')'=>['shift','68'],
},
{# state 39
  ')'=>['shift','69'],
},
{# state 40
  ')'=>['shift','70'],
},
{# state 41
  'BINNUM'=>['shift','19'],
  'DECNUM'=>['shift','21'],
  'HEXNUM'=>['shift','20'],
  'SYMNUM'=>['shift','22'],
  'constant'=>['goto','71'],
},
{# state 42
  ';'=>['shift','72'],
},
{# state 43
  'argument'=>['goto','35'],
  'expression'=>['goto','30'],
  '~'=>['shift','27'],
  'arguments'=>['goto','34'],
  'operator1'=>['goto','36'],
  'constant'=>['goto','32'],
  '-'=>['shift','28'],
  '('=>['shift','26'],
  'SYMNUM'=>['shift','22'],
  'NOT'=>['shift','24'],
  'nested_expression'=>['goto','31'],
  'BINNUM'=>['shift','19'],
  'IDENT'=>['shift','23'],
  '$default'=>['reduce','30'],
  'INT'=>['shift','25'],
  'DECNUM'=>['shift','21'],
  'HEXNUM'=>['shift','20'],
  'opt_arguments'=>['goto','73'],
  'variable'=>['goto','29'],
},
{# state 44
  ')'=>['shift','74'],
},
{# state 45
  '$default'=>['reduce','46'],
},
{# state 46
  '$default'=>['reduce','47'],
},
{# state 47
  '$default'=>['reduce','45'],
},
{# state 48
  '$default'=>['reduce','40'],
},
{# state 49
  '$default'=>['reduce','39'],
},
{# state 50
  '$default'=>['reduce','41'],
},
{# state 51
  '$default'=>['reduce','42'],
},
{# state 52
  '$default'=>['reduce','43'],
},
{# state 53
  '$default'=>['reduce','44'],
},
{# state 54
  '$default'=>['reduce','48'],
},
{# state 55
  '$default'=>['reduce','49'],
},
{# state 56
  '$default'=>['reduce','50'],
},
{# state 57
  '$default'=>['reduce','51'],
},
{# state 58
  '$default'=>['reduce','52'],
},
{# state 59
  '$default'=>['reduce','53'],
},
{# state 60
  '$default'=>['reduce','54'],
},
{# state 61
  '$default'=>['reduce','55'],
},
{# state 62
  'nested_expression'=>['goto','75'],
  'BINNUM'=>['shift','19'],
  'IDENT'=>['shift','23'],
  'DECNUM'=>['shift','21'],
  'HEXNUM'=>['shift','20'],
  'variable'=>['goto','29'],
  'constant'=>['goto','32'],
  '('=>['shift','26'],
  'SYMNUM'=>['shift','22'],
},
{# state 63
  ';'=>['shift','76'],
},
{# state 64
  '~'=>['shift','27'],
  'expression'=>['goto','30'],
  'argument'=>['goto','77'],
  'operator1'=>['goto','36'],
  'NOT'=>['shift','24'],
  'SYMNUM'=>['shift','22'],
  '('=>['shift','26'],
  'constant'=>['goto','32'],
  '-'=>['shift','28'],
  'BINNUM'=>['shift','19'],
  'nested_expression'=>['goto','31'],
  'DECNUM'=>['shift','21'],
  'INT'=>['shift','25'],
  'IDENT'=>['shift','23'],
  'variable'=>['goto','29'],
  'HEXNUM'=>['shift','20'],
},
{# state 65
  '$default'=>['reduce','21'],
},
{# state 66
  'variable'=>['goto','29'],
  'HEXNUM'=>['shift','20'],
  'DECNUM'=>['shift','21'],
  'IDENT'=>['shift','23'],
  'INT'=>['shift','25'],
  'nested_expression'=>['goto','31'],
  'BINNUM'=>['shift','19'],
  'NOT'=>['shift','24'],
  'SYMNUM'=>['shift','22'],
  'constant'=>['goto','32'],
  '-'=>['shift','28'],
  '('=>['shift','26'],
  'operator1'=>['goto','36'],
  '~'=>['shift','27'],
  'expression'=>['goto','78'],
},
{# state 67
  '$default'=>['reduce','17'],
},
{# state 68
  '{'=>['shift','79'],
  'STAGE'=>['shift','5'],
  'statement'=>['goto','80'],
  'IF'=>['shift','6'],
  'block_or_statement'=>['goto','81'],
  'block'=>['goto','82'],
  'DbgThrow'=>['shift','8'],
  'REPEAT'=>['shift','9'],
  'IDENT'=>['shift','4'],
  'variable'=>['goto','11'],
  'THROW'=>['shift','7'],
},
{# state 69
  ';'=>['shift','83'],
},
{# state 70
  ';'=>['shift','84'],
},
{# state 71
  'FOR'=>['shift','85'],
},
{# state 72
  '$default'=>['reduce','7'],
},
{# state 73
  ')'=>['shift','86'],
},
{# state 74
  '$default'=>['reduce','25'],
},
{# state 75
  '$default'=>['reduce','20'],
},
{# state 76
  '$default'=>['reduce','8'],
},
{# state 77
  '$default'=>['reduce','33'],
},
{# state 78
  ']'=>['shift','87'],
},
{# state 79
  'statements'=>['goto','88'],
  '$default'=>['reduce','2'],
},
{# state 80
  '$default'=>['reduce','13'],
},
{# state 81
  '$default'=>['reduce','5'],
  'ELSE'=>['shift','89'],
},
{# state 82
  '$default'=>['reduce','14'],
},
{# state 83
  '$default'=>['reduce','9'],
},
{# state 84
  '$default'=>['reduce','10'],
},
{# state 85
  'HEXNUM'=>['shift','20'],
  'DECNUM'=>['shift','21'],
  'BINNUM'=>['shift','19'],
  'SYMNUM'=>['shift','22'],
  'constant'=>['goto','90'],
},
{# state 86
  '$default'=>['reduce','24'],
},
{# state 87
  '$default'=>['reduce','18'],
},
{# state 88
  'IF'=>['shift','6'],
  'statement'=>['goto','10'],
  'STAGE'=>['shift','5'],
  'REPEAT'=>['shift','9'],
  'IDENT'=>['shift','4'],
  'DbgThrow'=>['shift','8'],
  'THROW'=>['shift','7'],
  '}'=>['shift','91'],
  'variable'=>['goto','11'],
},
{# state 89
  'variable'=>['goto','11'],
  'THROW'=>['shift','7'],
  'block'=>['goto','82'],
  'IDENT'=>['shift','4'],
  'REPEAT'=>['shift','9'],
  'DbgThrow'=>['shift','8'],
  'statement'=>['goto','80'],
  'STAGE'=>['shift','5'],
  'IF'=>['shift','6'],
  'block_or_statement'=>['goto','92'],
  '{'=>['shift','79'],
},
{# state 90
  'block'=>['goto','82'],
  'REPEAT'=>['shift','9'],
  'IDENT'=>['shift','4'],
  'DbgThrow'=>['shift','8'],
  'variable'=>['goto','11'],
  'THROW'=>['shift','7'],
  '{'=>['shift','79'],
  'statement'=>['goto','80'],
  'STAGE'=>['shift','5'],
  'block_or_statement'=>['goto','94'],
  'IF'=>['shift','6'],
  'STEP'=>['shift','93'],
},
{# state 91
  '$default'=>['reduce','15'],
},
{# state 92
  '$default'=>['reduce','6'],
},
{# state 93
  'BINNUM'=>['shift','19'],
  'DECNUM'=>['shift','21'],
  'HEXNUM'=>['shift','20'],
  'constant'=>['goto','95'],
  'SYMNUM'=>['shift','22'],
},
{# state 94
  '$default'=>['reduce','11'],
},
{# state 95
  'statement'=>['goto','80'],
  'STAGE'=>['shift','5'],
  'block_or_statement'=>['goto','96'],
  'IF'=>['shift','6'],
  '{'=>['shift','79'],
  'variable'=>['goto','11'],
  'THROW'=>['shift','7'],
  'block'=>['goto','82'],
  'REPEAT'=>['shift','9'],
  'IDENT'=>['shift','4'],
  'DbgThrow'=>['shift','8'],
},
{# state 96
  '$default'=>['reduce','12'],
},
);

our @length = (
2, 1, 0, 2, 1, 5, 7, 4, 5, 5, 5, 7, 9, 1, 1, 3, 1, 4, 6, 1, 3, 2, 1, 1, 4, 3, 1, 1, 1, 1, 0, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, );

our @rhs = ('$accept', 'takumi', 'statements', 'statements', 'statement', 'statement', 'statement', 'statement', 'statement', 'statement', 'statement', 'statement', 'statement', 'block_or_statement', 'block_or_statement', 'block', 'variable', 'variable', 'variable', 'expression', 'expression', 'expression', 'nested_expression', 'nested_expression', 'nested_expression', 'nested_expression', 'constant', 'constant', 'constant', 'constant', 'opt_arguments', 'opt_arguments', 'arguments', 'arguments', 'argument', 'operator1', 'operator1', 'operator1', 'operator1', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', 'operator2', );

# py-skel.pl: perl yacc parser skeleton
# Copyright 1995 Mark-Jason Dominus (mjd@pobox.com).
# Hacked 2001 Benoit Dupont de Dinechin (benoit@dinechin.org):
#  - use my variables instead of local wherever possible
#  - replace the soft reference ${rule_$d} code by $sem[$d]
#  - replace %act by @act to avoid split while parsing
# Hacked 2002 Christophe Guillon
#  - handling of empty rules (reduce and go)

sub yyparse {
  my @states = ();			# State stack
  my @values = ();			# Value stack
  my ($state, $nextplease, $lookahead) = (0, 1);
  for (;;) {
    $lookahead = &yylex if $nextplease;
    my $act = ${$act[$state]}{$lookahead} ||
	${$act[$state]}{'$default'} ||
	${$act[$state]}{'$end'} ||
	${$act[$state]}{'$'};
    unless (defined($act)) {		# Wrong token
      until (${$act[$state]}{'error'}) {
	$state = pop @states || return 1;
      }
    }
    my ($a, $d) = @$act;
    if ($a eq 'shift') {
      push(@values, $yylval);
      push(@states, $state);
      $state = $d;
      $nextplease = 1;
    } elsif ($a eq 'reduce') {
      my @args = ();
      @args = splice(@values, -$length[$d]) if $length[$d] > 0; # CG: handling of empty rules.
      my ($value) = (&{$sem[$d]}(@args));			# BD3: ensure only one value.
      push (@values, $value);
      push(@states, $state);					# CG: always push state.
      splice(@states, -$length[$d]) if $length[$d] > 0;		# CG: handling of empty rules, we stay in the same state.
      $state = $states[$#states];
      my $rhs = $rhs[$d];
      my $act = ${$act[$state]}{$rhs};
      my ($a, $d) = @$act;
      if ($a eq 'goto') {
	$state = $d;
      } else {
	print STDERR "Reduction to $rhs in state $state: ";
	print STDERR "action was $a, should have been a goto.\n";
	return 1;
      }
      $nextplease = 0;
    } elsif ($a eq 'goto') {
      $state = $d;
      $nextplease = 0;
    } elsif ($a eq 'accept') {
      return 0;
    } else {
      die "Unrecognized parsing action $a.\n";
    }
  }
}
#    END py-skel.pl

1;
